netlify/netlify-dev-plugin

src/detectors/vuepress.js
**- Summary**
Running `netlify dev` doesn't work for vuepress projects. This fix adds a detector so that the dev server can run. 
Add vuepress to your project
```
yarn add -D vuepress # OR npm install -D vuepress
mkdir docs
echo '# Hello VuePress' > docs/README.md
```
Then update your package.json file so it has the proper command for running vuepress. 
```
{
"scripts": {
"dev": "yarn run docs:dev",
}
}
```
Try running `netlify dev`. You should have a netlify dev server accessible at localhost:8888
Adds Vuepress to the list of detectors
**- A picture of a cute animal**
=> Add vuepress detector

src/cli-logo.js, src/commands/dev/exec.js, src/commands/dev/index.js, src/commands/functions/build.js, src/commands/functions/create.js, src/commands/functions/serve.js, src/commands/functions/update.js, src/detect-server.js, src/live-tunnel.js, src/utils/dev.js
=> just use ◈ instead of overly wordy branding

src/commands/dev/index.js, src/detectors/utils/jsdetect.js
**- Summary**
i had a misunderstanding of how execa works. need to supply "npm" to its "command", not "npm run", or it just dies.
fixes https://github.com/netlify/netlify-dev-plugin/issues/110
=> fix npm run bug with execa

src/detectors/nuxt.js
**- Summary**
@lunaceee and I paired yesterday and realized that a couple of Vue specific SSGs were not yet supported, including Nuxt and Vuepress (which has since been merged, yay!). This PR adds Nuxt to the SSG detectors so it builds properly.
```
yarn create nuxt-app <project-name>
cd <project-name>
netlify dev
```
Adds Nuxt detector
**- A picture of a cute animal**
=> fix: Add Nuxt

src/live-tunnel.js
Or if you want to require it only near the console log statement.
**- Summary**
Chalk was not defined
Let's migrate to typescript 😅 
Now logs correctly if you have not run `netlify init`
=> Chalk was not defined

package-lock.json, package.json, src/utils/serve-functions.js
**- Summary**
When the Netlify function is invoked with an Authorization header containing a bearer token, this decodes the information inside the token and populates the client context, just like the production environment does.
This is a straight up port of the same functionality from [this netlify-lambda PR](https://github.com/netlify/netlify-lambda/pull/57) and is crucial for local development of functions that use authentication.
Just like in netlify-lambda, _this doesn't actually validate the token, it only decodes the public part and injects it into the invocation._
Proper testing support doesn't seem to be in place yet, so I tested this change by compiling the Netlify cli locally with this fork of the netlify-dev-plugin in place, and everything ran well.
The info …
=> Inject client context into functions

src/detectors/quasar-v0.17.js, src/detectors/quasar.js
Since Quasar is in beta for v1.0 and has some differences this adds a detector for the latest pre-beta & v1.0 beta.
=> feat: Add detectors for Quasar v0.17 & v1.0 beta

src/commands/functions/create.js
Fix https://community.netlify.com/t/function-scaffolding-via-cli/600/4
=> update log message

src/utils/serve-functions.js
**- Summary**
Binary bodies where mangled by utf-8 encoding. Now we try to use the bodyParser.raw for binary and bodyParser.text for textual content.
My tests are mainly the actions described in issue #143.
handle binary request body using buffer
https://www.youtube.com/watch?v=BjkuMFZBJ3k
=> Handle binary request body using buffer: intends to fix #143

src/commands/dev/index.js
When starting the proxy we first check if proxyPort is free and otherwise we pick a random free port.
The live tunnel would always connect to the port specified in the settings, so in that case it would
start serving the wrong dev server on the .live domain.
This makes sure we pass on the new port to the live tunnel if changed
=> Fix live tunnel port when proxyPort is taken

src/commands/dev/index.js, src/detect-server.js
**Make defining npm scripts other than `start` possible in dev command**
The behavior was already described in #119. When using npm and defining configuring another command than `npm start` in the `command` field the script execution fails. This is because currently the command get's inserted an additional `run` argument when npm was detected. 
Exception:
```
Waiting for localhost:7894.npm ERR! missing script: run
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sjudis/.npm/_logs/2019-05-03T19_11_15_952Z-debug.log
FAIL: 1
```
I believe that it'd be better to always pass the arguments through to execution because this is what users are used to from the build section of the `netlify.toml`.
To test this I added a `netlify.toml` file to this repo as …
=> Fix dev command when running with npm - fix #119

src/detectors/middleman.js
**- Summary**
Add a detector for [Middleman](https://middlemanapp.com/).
n/a
Add Middleman detector.
=> Add Middleman detector

src/utils/serve-functions.js
**- Summary**
Changes the file watching mechanism to watch all files in the functions folder. Whenever any file is updated or removed, require.cache is cleared so the changes go live. This change enables hot reloading for functions with multiple files. 
Run netlify dev and modify a file required by a function. In the console, a message will appear that the file was modified and the new code will be run correctly.
Enable hot reloading for unbundled functions with multiple files
=> update serve-functions to watch all files in functions folder, fixes #167

src/detectors/middleman.js
**- Summary**
This PR fixes issue #177, an error in the Middleman detector added in #172.
Running `npm test` in the project's root folder throws a bunch of unrelated errors, but… the change here mimics other detectors in this repo (especially the `jekyll.js` detector.
Change uses the existing `existsSync` imported function rather than the unimported `hasRequiredFiles` that was throwing the errors reported in #177.
=> Use `existsSync` instead of `hasRequiredFiles` (fixes #177)

src/utils/serve-functions.js
**- Summary**
`netlify dev --live` fails to start if the functions directory doesn't exist.
Given the fact that `netlify init` doesn't create functions directory by default, the first-time experience of netlify dev is 😔
1. Init a project with netlify init
2. Try running `netlify dev --live`
Don't assume functions directory, check if it exists.
=> Check if functions directory exists. Fixes #182

src/detectors/sapper.js, src/detectors/svelte.js
**- Summary**
Now that Svelte 3 is out, we should support svelte projects on Netlify Dev 
Run an example svelte project. 
Sapper:
```
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
netlify dev
```
Svelte: 
```
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
netlify dev
```
Adds Svelte and Sapper to list of detectors
=> Add svelte and sapper to list of detectors

src/commands/functions/list.js, src/utils/get-functions.js, src/utils/serve-functions.js
**- Summary**
its small, people want to check that their functions are properly formatted. theres more potential for local validation (`functions doctor`?) generally.
closes https://github.com/netlify/netlify-dev-plugin/issues/209
pulling out the functions parsing to a separate file also helps us write other functionality.
run `ntl functions:list` to see your locally correctly configured functions.
=> implement basic netlify functions:list command

src/commands/dev/index.js
**- Summary**
Allow the user to run more than one dev server at one time.
* Run `netlify dev` in your project directory
* Run `netlify dev` in a different project directory
For the static server, we have moved from the absolute `proxyPort: 3999` to `getPort` method that chooses an available port.
For the `8888` server port, we use dynamic port from `getPort` if the user hasn't specified `port` in their `config`.
=> Make ports for local server dynamic

src/commands/dev/index.js, src/function-builder-detectors/netlify-lambda.js
**- Summary**
i was running into user confusion because i had a fully specified netlify dev block but it still looked like i was using the netlify project detection when it should have skipped all that:
in reality what was happening was that it was a funciton buidler running unintentionally. this is magic and the least we can do is tell people we're doing it so they can yell at us.
warn before running function builder
https://imgur.com/Inbn1BR
=> warn before running function builder

src/commands/functions/invoke.js
To avoid conflict with global `--auth` flag https://github.com/netlify/cli-utils/pull/13 we need to change this flag to `--identity`
=> change `—auth` flag to `—identity`

package.json, src/commands/dev/index.js
**- Summary**
`create-react-app` script was using ANSI to clear the screen before we could display our own information. This change disables the handing over of terminal to child script, and buffering output from it. When `create-react-app` detects that it is not attached to a terminal, it does not clear screen.
Fixes: https://github.com/netlify/cli/issues/374
* `npx create-react-app my-new-cra`
* `cd my-new-cra`
* `netlify dev`
Before: 
After:
* Dont handover terminal to child scripts
* Buffer `stdout` and `stderr` from child scripts to terminal
=> Don't allow child scripts to manipulate terminal

src/functions-templates/js/fauna-graphql/sync-schema.js
before: `Invalid authorization header.` when running `sync-schema`.
=> fix: authorization for sync-schema
